version: "2"
checks:
  method-lines:
    config:
      threshold: 50
exclude_patterns:
  - "public/**"
  - "src-tauri/**"
  - "**/*.d.ts"
  - "**/node_modules/"
  - "**/*.test.*"
  - "**/mocks.ts"
  - "**/types.ts"
  - "**/testUtils.tsx"